language: generic
sudo: required
services:
  - docker
before-install:
  - docker build -t vominhtuan164/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true vominhtuan164/docker-react npm run test
